version: '3.5'

services:
  nginx:
    image: "nginx:alpine"
    container_name: docker-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./code:/code
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./docker/nginx/localhost.key:/etc/ssl/private/localhost.key

